name: Run Tests

on:
  workflow_call:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Set node version to 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Run unit tests
      run: pnpm test
    - name: Run linter
      run: pnpm lint